devices:
  powerstreams:
    - HW51xxxxxxxxxxxx
mqtt:
  ecoflow:
    url: ssl://192.168.0.111:8883
  home-assistant:
    url: tcp://192.168.0.113:1883
    username: mosquitto
    password: secret
  enable-discovery: true