services:
  mqtt:
    image: eclipse-mosquitto:2.0.21-openssl
    container_name: "mqtt"
    restart: always
    ports:
      - 8883:8883
      - 1883:1883
    volumes:
      - /home/haos/docker/mosquitto/data:/mosquitto/data
      - /home/haos/docker/mosquitto/config:/mosquitto/config
      - /home/haos/docker/mosquitto/logs:/mosquitto/log
  psbridge:
    image: ghcr.io/tomvd/psbridge:latest
    container_name: "psbridge"
    restart: always
    volumes:
      - /home/haos/docker/psbridge/application.yml:/home/app/application.yml
    environment:
      MICRONAUT_CONFIG_FILES: '/home/app/application.yml'
    depends_on:
      - mqtt