devices:
  powerstreams:
    - HW51xxxxxxxxxxxx
  batteries:
    - R621xxxxxxxxxxxx
mqtt:
  ecoflow:
    url: ssl://localhost:8883
  home-assistant:
    url: tcp://localhost:1883
    username: mosquitto
    password: secret
  enable-discovery: true