devices:
  powerstreams:
    - HW51xxxxxxxxxxxx
  batteries:
    - R621xxxxxxxxxxxx
mqtt:
  client:
    server-uri: tcp://localhost:1883
    user-name: mosquitto
    password: secret
    enable-discovery: true
smart:
  enabled: true
  meter-topic: smart/p1
  enabled-topic: smart/enabled
  charger-topic: smart/charger
  soc-topic: smart/soc
  max-power: 333